In [1]:
import pandas as pd
import numpy as np
import mitosheet

## 1-Abro train.parquet

In [2]:
train = pd.read_parquet(r"C:\Users\ornal\Desktop\CursoDataScience\Datathon\train.parquet")
test = pd.read_parquet(r"C:\Users\ornal\Desktop\CursoDataScience\Datathon\test.parquet")

# Empezamos con
## train.info()
   #### RangeIndex: 346479 entries, 0 to 346478
   #### Data columns (total 22 columns):
   #### dtypes: float64(3), int64(10), object(9)
   #### memory usage: 58.2+ MB

## 2- Vamos a mejorar esos 58.2+ MB

In [3]:
train['region'] = train['region'].astype('category')
train['type'] = train['type'].astype('category')
train['state'] = train['state'].astype('category')
# int16 
train['sqfeet'] = train['sqfeet'].astype('int16')

# int8 
train['beds'] = train['beds'].astype('int8')
train['cats_allowed'] = train['cats_allowed'].astype('int8')
train['dogs_allowed'] = train['dogs_allowed'].astype('int8')
train['smoking_allowed'] = train['smoking_allowed'].astype('int8')
train['wheelchair_access'] = train['wheelchair_access'].astype('int8')
train['electric_vehicle_charge'] = train['electric_vehicle_charge'].astype('int8')
train['comes_furnished'] = train['comes_furnished'].astype('int8')

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346479 entries, 0 to 346478
Data columns (total 22 columns):
 #   Column                   Non-Null Count   Dtype   
---  ------                   --------------   -----   
 0   id                       346479 non-null  int64   
 1   url                      346479 non-null  object  
 2   region                   346479 non-null  category
 3   region_url               346479 non-null  object  
 4   price                    346479 non-null  int64   
 5   type                     346479 non-null  category
 6   sqfeet                   346479 non-null  int16   
 7   beds                     346479 non-null  int8    
 8   baths                    346479 non-null  float64 
 9   cats_allowed             346479 non-null  int8    
 10  dogs_allowed             346479 non-null  int8    
 11  smoking_allowed          346479 non-null  int8    
 12  wheelchair_access        346479 non-null  int8    
 13  electric_vehicle_charge  346479 non-null  in

In [4]:
test['region'] = test['region'].astype('category')
test['type'] = test['type'].astype('category')
test['state'] = test['state'].astype('category')
# int16 
test['sqfeet'] = test['sqfeet'].astype('int16')

# int8 
test['beds'] = test['beds'].astype('int8')
test['cats_allowed'] = test['cats_allowed'].astype('int8')
test['dogs_allowed'] = test['dogs_allowed'].astype('int8')
test['smoking_allowed'] = test['smoking_allowed'].astype('int8')
test['wheelchair_access'] = test['wheelchair_access'].astype('int8')
test['electric_vehicle_charge'] = test['electric_vehicle_charge'].astype('int8')
test['comes_furnished'] = test['comes_furnished'].astype('int8')

test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38498 entries, 0 to 38497
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype   
---  ------                   --------------  -----   
 0   id                       38498 non-null  int64   
 1   url                      38498 non-null  object  
 2   region                   38498 non-null  category
 3   region_url               38498 non-null  object  
 4   type                     38498 non-null  category
 5   sqfeet                   38498 non-null  int16   
 6   beds                     38498 non-null  int8    
 7   baths                    38498 non-null  float64 
 8   cats_allowed             38498 non-null  int8    
 9   dogs_allowed             38498 non-null  int8    
 10  smoking_allowed          38498 non-null  int8    
 11  wheelchair_access        38498 non-null  int8    
 12  electric_vehicle_charge  38498 non-null  int8    
 13  comes_furnished          38498 non-null  int8    
 14  laundr

## Hasta ahora tenemos
#### RangeIndex: 346479 entries, 0 to 346478
#### Data columns (total 22 columns):
#### dtypes: category(3), float16(1), float64(2), int16(1), int64(2), int8(7), object(6)
#### memory usage: 33.4+ MB

## 3- Busco los nulos
#### laundry_options             71171
#### parking_options            126682
#### lat                          1722
#### long                         1722

In [5]:
train.isnull().sum()

id                              0
url                             0
region                          0
region_url                      0
price                           0
type                            0
sqfeet                          0
beds                            0
baths                           0
cats_allowed                    0
dogs_allowed                    0
smoking_allowed                 0
wheelchair_access               0
electric_vehicle_charge         0
comes_furnished                 0
laundry_options             71171
parking_options            126682
image_url                       0
description                     2
lat                          1722
long                         1722
state                           0
dtype: int64

In [6]:
test.isnull().sum()

id                             0
url                            0
region                         0
region_url                     0
type                           0
sqfeet                         0
beds                           0
baths                          0
cats_allowed                   0
dogs_allowed                   0
smoking_allowed                0
wheelchair_access              0
electric_vehicle_charge        0
comes_furnished                0
laundry_options             7855
parking_options            14005
image_url                      0
description                    0
lat                          196
long                         196
state                          0
dtype: int64

## 4- Tratamiento a nulos

## 4.1- laundry_options

In [7]:
train['laundry_options'].unique()

array(['w/d in unit', 'w/d hookups', 'laundry on site', None,
       'laundry in bldg', 'no laundry on site'], dtype=object)

None               = 0
w/d in unit        = 1
w/d hookups        = 2
laundry on site    = 3
laundry in bldg    = 4
no laundry on site = 0

In [53]:
def laundry(x):
  match x:
    case 'no laundry on site':
        return 0
    case 'w/d in unit':
        return 1
    case 'w/d hookups':
        return 2
    case 'laundry on site':
        return 3
    case 'laundry in bldg':
        return 4
    case _: # None
        return 0

In [9]:
train['laundry_options'] = train['laundry_options'].apply(laundry)
test['laundry_options'] = test['laundry_options'].apply(laundry)

In [10]:
train['laundry_options'].unique()

array([1, 2, 3, 0, 4], dtype=int64)

In [11]:
test['laundry_options'].unique()

array([1, 2, 3, 0, 4], dtype=int64)

In [12]:
train['laundry_options'] = train['laundry_options'].astype('int8')
test['laundry_options'] = test['laundry_options'].astype('int8')

## 4.2- parking_options

In [13]:
train['parking_options'].unique()

array(['detached garage', 'carport', 'off-street parking', None,
       'attached garage', 'street parking', 'no parking', 'valet parking'],
      dtype=object)

None               = 0
detached garage    = 1
carport            = 2
off-street parking = 3
attached garage    = 4
street parking     = 5
valet parking      = 6
no parking         = 0

In [14]:
def parking(x):
  match x:
    case 'no parking':
        return 0
    case 'detached garage':
        return 1
    case 'carport':
        return 2
    case 'off-street parking':
        return 3
    case 'attached garage':
        return 4
    case 'street parking':
        return 5
    case 'valet parking':
        return 6
    case _: # None
        return 0

In [15]:
train['parking_options'] = train['parking_options'].apply(parking)
test['parking_options'] = test['parking_options'].apply(parking)

In [16]:
train['parking_options'].unique()

array([1, 2, 3, 0, 4, 5, 6], dtype=int64)

In [17]:
test['parking_options'].unique()

array([3, 2, 4, 0, 5, 1, 6], dtype=int64)

In [18]:
train['parking_options'] = train['parking_options'].astype('int8')
test['parking_options'] = test['parking_options'].astype('int8')

## 4.3- lat y long no los voy a usar

In [19]:
train.drop(['id','url','region_url','image_url','description','lat','long'],axis='columns',inplace=True)
test.drop(['id','url','region_url','image_url','description','lat','long'],axis='columns',inplace=True)

In [20]:
#nulos = train[train['lat'].isnull() & train['long'].isnull()]
#no_nulos = train[train['lat'].notna() & train['long'].notna()]

In [21]:
#print(nulos.shape[0]+no_nulos.shape[0],train.shape[0])

In [22]:
'''for index,row in nulos.iterrows():
    temp = train[(train.state == row.state) & (train.region == row.region)]
    if temp.shape[0] > 0:
        nulos.loc[nulos.id == row.id,'lat'] = temp.iloc[0]['lat']
        nulos.loc[nulos.id == row.id,'long'] = temp.iloc[0]['long']'''

"for index,row in nulos.iterrows():\n    temp = train[(train.state == row.state) & (train.region == row.region)]\n    if temp.shape[0] > 0:\n        nulos.loc[nulos.id == row.id,'lat'] = temp.iloc[0]['lat']\n        nulos.loc[nulos.id == row.id,'long'] = temp.iloc[0]['long']"

In [23]:
#train1 = pd.concat([nulos,no_nulos])

In [24]:
#train1.isnull().sum()

In [25]:
train.isnull().sum()

region                     0
price                      0
type                       0
sqfeet                     0
beds                       0
baths                      0
cats_allowed               0
dogs_allowed               0
smoking_allowed            0
wheelchair_access          0
electric_vehicle_charge    0
comes_furnished            0
laundry_options            0
parking_options            0
state                      0
dtype: int64

In [26]:
test.isnull().sum()

region                     0
type                       0
sqfeet                     0
beds                       0
baths                      0
cats_allowed               0
dogs_allowed               0
smoking_allowed            0
wheelchair_access          0
electric_vehicle_charge    0
comes_furnished            0
laundry_options            0
parking_options            0
state                      0
dtype: int64

## 5- Continúo con la codificación de la información

## 5.1- Creo un clasificador de regiones

In [27]:
region = pd.DataFrame(list(train.region.unique()),
                     index = range(1,len(list(train.region.unique()))+1),
                     columns = ['nombre']                 
                     )

In [28]:
region.to_csv(r"C:\Users\ornal\Desktop\CursoDataScience\Datathon\region.csv")

In [29]:
def regiones(x):
    return region.index[region['nombre'] == x].tolist()[0]

In [30]:
train['region'] = train['region'].apply(regiones)

In [31]:
test['region'] = test['region'].apply(regiones)

In [32]:
train['region'] = train['region'].astype('int16')
test['region'] = test['region'].astype('int16')

## 5.2- Creo un clasificador de estados

In [33]:
state = pd.DataFrame(list(train.state.unique()),
                     index = range(1,len(list(train.state.unique()))+1),
                     columns = ['nombre']                 
                     )

In [34]:
state.to_csv(r"C:\Users\ornal\Desktop\CursoDataScience\Datathon\state.csv")

In [35]:
def states(x):
    return state.index[state['nombre'] == x].tolist()[0]

In [36]:
train['state'] = train['state'].apply(states)

In [37]:
test['state'] = test['state'].apply(states)

## 5.3- Creo un Clasificador de types

In [38]:
tipo = pd.DataFrame(list(train.type.unique()),
                     index = range(1,len(list(train.type.unique()))+1),
                     columns = ['nombre']                 
                     )

In [39]:
tipo.to_csv(r"C:\Users\ornal\Desktop\CursoDataScience\Datathon\tipo.csv")

In [40]:
def tipos(x):
    return tipo.index[tipo['nombre'] == x].tolist()[0]

In [41]:
train['type'] = train['type'].apply(tipos)

In [42]:
test['type'] = test['type'].apply(tipos)

## 6- Crear columna category_price

In [43]:
def cat_price(x):
    if x < 1000:
        return 1
    return 0

### 6.1- Primero elilimino los precios sin sentido

In [44]:
train.drop(train[train['price'] < 90].index, inplace=True)

In [45]:
train['category_price'] = train['price'].apply(cat_price)

### 6.2- Elimino columna price

In [46]:
train.drop(['price'],axis='columns',inplace=True)

In [54]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 344512 entries, 0 to 346478
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype   
---  ------                   --------------   -----   
 0   region                   344512 non-null  int16   
 1   type                     344512 non-null  category
 2   sqfeet                   344512 non-null  int16   
 3   beds                     344512 non-null  int8    
 4   baths                    344512 non-null  float64 
 5   cats_allowed             344512 non-null  int8    
 6   dogs_allowed             344512 non-null  int8    
 7   smoking_allowed          344512 non-null  int8    
 8   wheelchair_access        344512 non-null  int8    
 9   electric_vehicle_charge  344512 non-null  int8    
 10  comes_furnished          344512 non-null  int8    
 11  laundry_options          344512 non-null  int8    
 12  parking_options          344512 non-null  int8    
 13  state                    344512 non-null  ca

## 7- Resumen

### Empezamos con
   dtypes: float64(3), int64(10), object(9)
   memory usage: 58.2+ MB

### Terminamos con
   dtypes: category(3), float16(3), int16(1), int64(2), int8(9), object(4)
   memory usage: 12.8 MB

## Salvo en disco los csv son para uso mio interno

In [47]:
train.to_parquet(r"C:\Users\ornal\Desktop\CursoDataScience\Datathon\train1.parquet",index=False)

In [48]:
test.to_parquet(r"C:\Users\ornal\Desktop\CursoDataScience\Datathon\test1.parquet",index=False)

In [49]:
train.to_csv(r"C:\Users\ornal\Desktop\CursoDataScience\Datathon\train1.csv",index=False)

In [50]:
test.to_csv(r"C:\Users\ornal\Desktop\CursoDataScience\Datathon\test1.csv",index=False)